# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('slug', models.SlugField(help_text=b'A label for URL config', max_length=63, unique_for_month=b'pub_date')),
                ('text', models.TextField()),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name=b'date published')),
            ],
            options={
                'ordering': ['-pub_date', 'title'],
                'permissions': (('view_future_post', 'Can view unpublished Post'),),
                'get_latest_by': 'pub_date',
                'verbose_name': 'blog post',
            },
        ),
    ]
