# Generated by Django 2.2.4 on 2019-09-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslink',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='founded_date',
            field=models.DateField(verbose_name='date founded'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='slug',
            field=models.SlugField(help_text='A label for URL config.', max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='A label for URL config.', max_length=31, unique=True),
        ),
    ]
